# Site settings
title: "Robert Scott Dionne: Blog"
email: robertsdionne-at-gmail-dot-com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer interested in Machine Learning and
  Natural Language Processing and Generation;
  MFA graduate from NYU Game Center.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://robertsdionne.github.io" # the base hostname & protocol for your site
twitter_username: robertsdionne
github_username:  robertsdionne
encoding: utf-8

# Build settings
markdown: kramdown
